# Feed Forward Neural Network From Scratch - MNIST Classification

## Loading MNIST Image Data

In [1]:
# Import built-in modules from Python's standard library
import gzip
import pickle

# Import Third-party libraries
import numpy as np

In [2]:
with gzip.open('../data/mnist.pkl.gz', 'rb') as f:
    training_data, validation_data, testing_data = pickle.load(f, encoding='latin1')

In [3]:
training_data

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(50000, 784), dtype=float32),
 array([5, 0, 4, ..., 8, 4, 8], shape=(50000,)))

In [4]:
validation_data

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 784), dtype=float32),
 array([3, 8, 6, ..., 5, 6, 8], shape=(10000,)))

In [5]:
testing_data

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], shape=(10000, 784), dtype=float32),
 array([7, 2, 1, ..., 4, 5, 6], shape=(10000,)))

In [6]:
print(f'training_data   : type = {type(training_data)},   length = {len(training_data)}')
print(f'validation_data : type = {type(validation_data)},   length = {len(validation_data)}')
print(f'testing_data    : type = {type(testing_data)},   length = {len(testing_data)}')

training_data   : type = <class 'tuple'>,   length = 2
validation_data : type = <class 'tuple'>,   length = 2
testing_data    : type = <class 'tuple'>,   length = 2


In [7]:
type(training_data[0])

numpy.ndarray

In [8]:
training_data[0].ndim

2

In [9]:
training_data[0].shape

(50000, 784)

In [10]:
type(training_data[1])

numpy.ndarray

In [11]:
training_data[1].ndim

1

In [12]:
training_data[1].shape

(50000,)

In [13]:
training_data[1][0], training_data[1][1], training_data[1][2], 

(np.int64(5), np.int64(0), np.int64(4))

In [14]:
type(training_data[0][0])

numpy.ndarray

In [15]:
training_data[0][0].shape

(784,)

In [16]:
training_features = [np.reshape(feature, (784, 1)) for feature in training_data[0]]

In [17]:
np.array(training_features).shape

(50000, 784, 1)

In [18]:
def vectorized_label(label):
    label_vector = np.zeros((10, 1))
    label_vector[label] = 1.0
    return label_vector

In [19]:
training_labels = [vectorized_label(label) for label in training_data[1]]

In [20]:
np.array(training_labels).shape

(50000, 10, 1)

In [21]:
train_data = list(zip(training_features, training_labels))

In [69]:
len(train_data)

50000

In [22]:
validation_features = [np.reshape(features, (784, 1)) for features in validation_data[0]]

In [23]:
np.array(validation_features).shape

(10000, 784, 1)

In [24]:
val_data = list(zip(validation_features, validation_data[1]))

In [25]:
testing_features = [np.reshape(features, (784, 1)) for features in testing_data[0]]

In [26]:
test_data = list(zip(testing_features, testing_data[1]))

## Initialize weights & biases

In [27]:
sizes = [784, 30, 10]

In [28]:
biases = [np.random.randn(size, 1) for size in sizes[1:]]

In [29]:
weights = [np.random.randn(next, curr) for curr, next in zip(sizes[:-1], sizes[1:])]

# weights = [np.random.randn(next_layer, curr_layer) / np.sqrt(curr_layer) for curr_layer, next_layer in zip(sizes[:-1], sizes[1:])]

## SGD

In [61]:
n = len(train_data)
epochs = 30
mini_batch_size = 10
eta = 3.0
n_test = len(test_data)

In [62]:
n

50000

In [63]:
epochs

30

In [64]:
mini_batch_size

10

In [65]:
eta 

3.0

In [66]:
n_test

10000

In [67]:
# Use the recommended Generator instance for new code
rng = np.random.default_rng()

In [92]:
for epoch in range(epochs):
    rng.shuffle(train_data)
    mini_batches = [train_data[k:k+mini_batch_size] for k in range(0, n, mini_batch_size)]

In [101]:
def update_mini_batch(mini_batch, eta):
    ...

In [102]:
for mini_batch in mini_batches:
    update_mini_batch(mini_batch, eta)

In [ ]:
def update_mini_batch(mini_batch, eta):
    """Update the network's weights and biases by applying
    gradient descent using backpropagation to a single mini batch.
    The ``mini_batch`` is a list of tuples ``(x, y)``, and ``eta``
    is the learning rate."""
    del_b = [np.zeros(b.shape) for b in biases]
    del_w = [np.zeros(w.shape) for w in weights]
    for x, y in mini_batch:
        delta_nabla_b, delta_nabla_w = self.backprop(x, y)
        nabla_b = [nb+dnb for nb, dnb in zip(nabla_b, delta_nabla_b)]
        nabla_w = [nw+dnw for nw, dnw in zip(nabla_w, delta_nabla_w)]
    weights = [w-(eta/len(mini_batch))*nw
                    for w, nw in zip(self.weights, nabla_w)]
    biases = [b-(eta/len(mini_batch))*nb
                   for b, nb in zip(self.biases, nabla_b)]

In [ ]:
def backprop(self, x, y):
    """Return a tuple ``(nabla_b, nabla_w)`` representing the
    gradient for the cost function C_x.  ``nabla_b`` and
    ``nabla_w`` are layer-by-layer lists of numpy arrays, similar
    to ``self.biases`` and ``self.weights``."""
    nabla_b = [np.zeros(b.shape) for b in self.biases]
    nabla_w = [np.zeros(w.shape) for w in self.weights]
    # feedforward
    activation = x
    activations = [x] # list to store all the activations, layer by layer
    zs = [] # list to store all the z vectors, layer by layer
    for b, w in zip(self.biases, self.weights):
        z = np.dot(w, activation)+b
        zs.append(z)
        activation = sigmoid(z)
        activations.append(activation)
    # backward pass
    delta = self.cost_derivative(activations[-1], y) * \
        sigmoid_prime(zs[-1])
    nabla_b[-1] = delta
    nabla_w[-1] = np.dot(delta, activations[-2].transpose())
    # Note that the variable l in the loop below is used a little
    # differently to the notation in Chapter 2 of the book.  Here,
    # l = 1 means the last layer of neurons, l = 2 is the
    # second-last layer, and so on.  It's a renumbering of the
    # scheme in the book, used here to take advantage of the fact
    # that Python can use negative indices in lists.
    for l in xrange(2, self.num_layers):
        z = zs[-l]
        sp = sigmoid_prime(z)
        delta = np.dot(self.weights[-l+1].transpose(), delta) * sp
        nabla_b[-l] = delta
        nabla_w[-l] = np.dot(delta, activations[-l-1].transpose())
    return (nabla_b, nabla_w)