# Linear Algebra

In [1]:
import numpy as np

# Basic Tensor Operations

## Normal Matrix Addition

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

# Normal Matrix Addition
C = A + B

print(C)

[[11 22 33]
 [44 55 66]]


## Broadcasting Addition

### Case 1: Add scalar

In [3]:
# Scalar is added to every element

C = A + 5
print(C)

[[ 6  7  8]
 [ 9 10 11]]


### Case 2: Add row vector

In [4]:
# Row vector is broadcasted across rows

v = np.array([10, 20, 30])
C = A + v
print(C)

[[11 22 33]
 [14 25 36]]


### Case 3: Add column vector

In [5]:
# Column vector is broadcasted across columns

v = np.array([[10],
              [20]])

C = A + v
print(C)

[[11 12 13]
 [24 25 26]]


## Matrix Multiplication

$$ C_{ij} = \sum_k A_{ik} B_{kj}$$

In [6]:
import numpy as np

A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

C = A @ B   # or np.matmul(A, B)

print(C)

[[19 22]
 [43 50]]


## Hadamard Product (Element-wise)

$$ C_{ij} = A_{ij} B_{ij} $$

In [7]:
# Multiply corresponding elements
# Same shape required

C = A * B

print(C)

[[ 5 12]
 [21 32]]


## Transpose

Swap rows and columns.

$$ A_{ij}^T = A_{ji} $$

### Transpose of a Matrix

In [8]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

AT = A.T

print(AT)

[[1 4]
 [2 5]
 [3 6]]


### Transpose of a Vector

In [9]:
v = np.array([1, 2, 3])

print(v.T)

[1 2 3]


👉 No change!

Because this is a 1D array, not a column vector.

In [10]:
v = np.array([[1],
              [2],
              [3]])

print(v.T)

[[1 2 3]]


### Transpose using function

In [11]:
np.transpose(v)

array([[1, 2, 3]])

## Dot Product of Vectors

$$\vec{a} \cdot \vec{b}= \mathbf{a}^T \mathbf{b} = \mathbf{b}^T \mathbf{a}$$ 

In [12]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

dot = np.dot(v1, v2)

print(dot)

32


# Norm

Norm is a way of measuring the "length" of vectors, matrices etc. Mathematically, a norm is any function $f$ that satisfies

- $ f(x) = 0 \implies x = 0 $
- $ f(x + y) \leq f(x) + f(y) $
- $ \forall  \alpha \in 	\mathbb{R}, f(\alpha x) = |\alpha|f(x) $

## Vector Norms

### $p$-norm / $L^p$-norm

$p$-norm / $L^p$-norm of a vector $\mathbf{𝑣} \in 	\mathbb{R}^n$

$$\left\| v \right\|_{p} = \left( |v_1|^p + |v_2|^p + |v_3|^p + \cdots + |v_n|^p \right)^{\frac{1}{p}}, \quad \text{for } p \geq 1 $$

$$\left\| v \right\|_{p} = \left( \sum_{i=1}^{n} |v_i|^p\right)^{\frac{1}{p}}, \quad \text{for } p \geq 1 $$

### $1$-norm / $L^1$-norm / Manhattan norm

$p=1$ → Manhattan norm

$$ \left\| v \right\|_{1} = |v_1| + |v_2| + |v_3| + \cdots + |v_n| $$ 

### $2$-norm / $L^2$-norm / Euclidean norm

$p=2$ → Euclidean norm (most common)

$$ \left\| v \right\|_2 = (v_1^2 + v_2^2 + v_3^2 + \cdots + v_n^2)^{\frac{1}{2}}$$

### Max norm

$p \to \infty$ → Max norm

$$\|v\|_{\infty} = \max_i |v_i| $$

In [13]:
import numpy as np

# Sample vector
v = np.array([3, -4, 2])

# ---------------------------
# L1 Norm (Manhattan)
# ---------------------------
l1 = np.sum(np.abs(v))

# ---------------------------
# L2 Norm (Euclidean)
# ---------------------------
l2 = np.sqrt(np.sum(v**2))

# ---------------------------
# General Lp Norm
# ---------------------------
def lp_norm(v, p):
    return np.sum(np.abs(v)**p) ** (1/p)

l3 = lp_norm(v, 3)   # example for p=3

# ---------------------------
# L-infinity Norm (Max norm)
# ---------------------------
linf = np.max(np.abs(v))

# ---------------------------
# Using built-in NumPy function
# ---------------------------
l1_np = np.linalg.norm(v, ord=1)
l2_np = np.linalg.norm(v, ord=2)
l3_np = np.linalg.norm(v, ord=3)
linf_np = np.linalg.norm(v, ord=np.inf)

# ---------------------------
# Print results
# ---------------------------
print("Vector:", v)
print("L1 norm:", l1)
print("L2 norm:", l2)
print("L3 norm:", l3)
print("L-infinity norm:", linf)

print("\nUsing np.linalg.norm:")
print("L1:", l1_np)
print("L2:", l2_np)
print("L3:", l3_np)
print("L-infinity:", linf_np)

Vector: [ 3 -4  2]
L1 norm: 9
L2 norm: 5.385164807134504
L3 norm: 4.626065009182741
L-infinity norm: 4

Using np.linalg.norm:
L1: 9.0
L2: 5.385164807134504
L3: 4.626065009182741
L-infinity: 4.0


## Matrix Norms

### Frobenius Norm

$$
\|A\|_F = \sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n} |a_{ij}|^2}
$$

In [14]:
# Example matrix
A = np.array([
    [1, -2, 3],
    [4, 0, -6]
])

# ---------------------------
# Frobenius norm
# ---------------------------
fro = np.sqrt(np.sum(A**2))

# ---------------------------
# Using built-in NumPy
# ---------------------------
fro_np = np.linalg.norm(A, ord='fro')

print("Frobenius:", fro)
print("Frobenius:", fro_np)

Frobenius: 8.12403840463596
Frobenius: 8.12403840463596


# Linear Combination of Vectors

A linear combination of the set of vectors $\{\mathbf{v_1}, \mathbf{v_2}, \cdots \mathbf{v_n}\}$ is given by multiplying each vector by a corresponding scalar coefficient and adding the results.

$$ \sum_{i=1}^n \alpha_i \mathbf{v_i}$$

# Matrix Myltiplication as a Linear Combination of Column Vectors

Matrix mutiplication can be interpreted in terms of the linear combination of the columns.

In [15]:
V = np.array([[1, 2], [2, 0], [3, 3]])
A = np.array([[1, 3], [2, 4]])

In [16]:
V @ A

array([[ 5, 11],
       [ 2,  6],
       [ 9, 21]])

In [17]:
1 * np.array([[1], [2], [3]]) + 2 * np.array([[2], [0], [3]])

array([[5],
       [2],
       [9]])

In [18]:
3 * np.array([[1], [2], [3]]) + 4 * np.array([[2], [0], [3]])

array([[11],
       [ 6],
       [21]])

# Span of a set of Vectors

The span of a set of vectors is the set of all the vectors obtainable by a linear combination of the original vectors.

Ex: The span of vectors $ \mathbf{v_1} = (1, 0)$, $\mathbf{v_2} = (0, 1)$ is whole of $\mathbb{R}^2$.

# Column Space of a Matrix

The span of all the columns of a matrix is called the column space.

Note: The equation $\mathbf{A} \mathbf{x} = \mathbf{b}$ has a solution only if $\mathbf{b}$ lies in the column space of $\mathbf{A}$.

# Linear Independence

A set of vectors are linearly independent if none of these vectors can be written as a linear combination of the other vectors.

Ex: 
- $ \mathbf{v_1} = (1, 0)$, $\mathbf{v_2} = (0, 1)$  are linearly independent.
- $ \mathbf{v_1} = (1, 0)$, $\mathbf{v_2} = (0, 1)$, $\mathbf{v_3} = (3, 4)$  are linearly dependent.

Mathematically, $\mathbf{S} = {\mathbf{v_1}, \mathbf{v_2}, \cdots, \mathbf{v_n}} $ are linearly independent if and only if the linear combination $\alpha_1 v_1 + \alpha_2 v_2 + \cdots + \alpha_n v_n = 0 $ means that all the $\alpha_i = 0$.